onboarding = false

[ui]
status_indicators = "symbols"
sidebar_start_collapsed = true
sidebar_collapsed_mode = "hidden"
pane_scrollbars = false
pane_gaps = false
hide_tab_bar_when_single_tab = true

[ui.toast]
delivery = "terminal"

[theme]
name = "nord"
auto_switch = false
